# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:calculationstool
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL logging (valgfrit)
logging.level.org.springframework.jdbc.core=DEBUG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
